축제 관리 기능 페이지 임시 코드입니다.
ToyVallet/swifty-root pull request #2
Opened 2024-05-29 02:24 UTC by hyunwlee-dev

2024-06-03 00:43 UTC, ho991217 requested changes
컨플릭트 해결 부탁드립니다

2024-06-03 07:23 UTC, kd02109 reviewed
수고하셨습니다. API 문제 수정했다고 하니 추가 연결 가능할 듯 합니다!

2024-06-03 07:23 UTC, kd02109 commented on src/app/(dashboard)/festivals/page.tsx
해당 페이지에 축제 생성 api도 연결이 되어야 할 것 같습니다!

2024-06-03 07:23 UTC, kd02109 commented on src/app/(dashboard)/festivals/[id]/page.tsx
페이지네이션 버튼의 숫자 위치가 중앙정렬이 아닌 것 같습니다. 
<img width="809" alt="image" src="https://github.com/ToyVallet/swifty-root/assets/57277708/a8efe714-c506-4eea-b788-fe2c084afbc6">

2024-06-03 07:23 UTC, kd02109 commented on src/app/(dashboard)/festivals/[id]/action.ts
> +    method: 'POST',
```suggestion
    method: 'POST',
    credential: 'include'
```
쿠키 전달을 하려면, 서버 액션에서도 credential 옵션을 사용해야 하지 않나요?

2024-06-03 07:23 UTC, kd02109 commented on src/app/components/ui/form/concert-create-form.tsx
component dir의 구조를 app router와 최대한 동일하게 가져 가면 좋을 것 같습니다. 이전 danfesta와 같이 특정 페이지에서만 고정적으로 활용하는 컴포넌트는 해당 app router 폴더 명과 동일하게 묶어서 쉽게 찾을 수 있도록 하면 좋을 듯합니다.

2024-06-03 07:23 UTC, kd02109 commented on src/app/components/ui/form/concert-create-form.tsx
아직 축제 관련 api가 서버랑 연결된 상태는 아닌거죠?

2024-06-03 07:23 UTC, kd02109 commented on src/app/(dashboard)/festivals/[id]/page.tsx
생성된 라인업에서 수정 삭제 뿐만 아니라, 한 depth 더 들어가서 상세 라인업 정보랑 이미지를 볼 수 있어야 한다고 생각합니다.!

2024-06-03 09:39 UTC, hyunwlee-dev commented on src/app/components/ui/form/concert-create-form.tsx
넵! 연결이 완료되고 pr수정 완료되면 알려드릴게요

2024-06-04 05:05 UTC, ho991217 requested changes

2024-06-04 05:05 UTC, ho991217 commented on public/icons/swifty-logo.svg
저희 로고와 컬러가 다르네요

2024-06-04 05:05 UTC, ho991217 commented on public/icons/swifty-logo-small.svg
저희 로고와 컬러가 다르네요

2024-06-04 05:05 UTC, ho991217 commented on public/icons/plus.svg
저희 로고와 컬러가 다르네요

2024-06-04 05:05 UTC, ho991217 commented on src/app/(dashboard)/festivals/[id]/action.ts
> +  console.log(`datas: ${datas}`);
```suggestion
```
불필요한 console.log는 지워주세요!

2024-06-04 06:28 UTC, kd02109 approved these changes

2024-06-04 06:28 UTC, kd02109 approved these changes

2024-06-04 06:49 UTC, ho991217 approved these changes

2024-06-04 06:49 UTC, merged