feat: login 기능 생성
ToyVallet/swifty-root pull request #9
Opened 2024-06-03 06:37 UTC by kd02109

close: #8 

- 쿠키 값에 맞추어 접근 페이지 제한
- 401 status가 발생할시 login으로 redirect 및 쿠키 삭제
- root 계정에서 활용하는 API constants 생성
- 로컬에서 동작하도록 host 수정 방법 작성
- custom fetch 생성

2024-06-03 10:07 UTC, kd02109 commented
```ts
export const SERVER_URL = 'https://dpi.swifty.kr' as const;

export const API_LINEUP = {
  lineup: (id?: string) => (id ? `/admin/line_up/${id}` : '/admin/line_up'),
} as const;

export const API_CLIENT = {
  host: (id?: string) => (id ? `/admin/host/${id}` : '/admin/host'),
} as const;

export const API_FESTIVAL = {
  lineup: (id?: string) => (id ? `/admin/festival/${id}` : '/admin/festival'),
  detail: (id: string) => `/admin/festival/detail/${id}`,
} as const;

export const API_SEARCH = {
  search: (q?: string) =>
    q ? `/festival/search?keyword=${q}` : `festival/search`,
} as const;

export const API_AUTH = {
  login: '/user/login',
} as const;

```

다음과 같이 수정 해당 객체에서 queryparmam이나 dynamicpath를 받아오는 방식을 별도 함수로 만들어 보려고 했으나 해당 방법은 page.tsx 내부에서 가능하기에 제외하고 기존의 방법으로 갔습니다. 데이터 형식을 객체로 모두 통일하고 객체의 프로퍼티가 하나라도 함수인 경우는 모두 함수로, 내부 프로퍼티가 모두 문자열로 관리할 수 있다면 문자열로 관리하도록 했습니다. 
const 타입으로 지정했기에 별도의 타입 추론은 필요없어서 만들지 않았습니다.

2024-06-04 00:52 UTC, ho991217 requested changes
고생하셨습니다!

2024-06-04 00:52 UTC, ho991217 commented on src/app/lib/contants.ts
API path를 객체로 관리하는 부분도 생각해볼만한 주제인 것 같아요

### 장점, 단점
**장점**
1. path 변경에 유연하게 대처할 수 있다.
2. API 호출 구문을 명시적으로 다룰 수 있다.

**단점**
1. depth가 깊어지면 문자열보다 더 길어진다. `/user/login` -> `API_PATH.user.login`


### 객체로 관리한다면
단점을 minimize 해야할 것 같아요!
그리고 AS-IS는 일부는 `string`, 일부는 메서드로 작성해주셨는데요, 전체를 함수로 바꾸는 방법도 고려해보면 좋을 것 같습니다!

+ 이렇게 하면 단건 조회, 다건 조회를 하나의 key로 관리할 수 있을 것 같습니다!
`lineup: (id?: string) => id ? '/admin/lineup/${id}' : '/admin/lineup\'`

2024-06-04 00:52 UTC, ho991217 commented on src/app/api/index.ts
> +    isExpiredRefresh(response);
이 함수 이름이 무엇을 하는지 정확하게 알기 어려운 것 같아요!

2024-06-04 00:52 UTC, ho991217 commented on src/app/api/index.ts
> +};
```suggestion
const isErrorResponse = (data: unknown): data is ErrorResponse => typeof data === 'object' && data !== null && 'message' in data;
```

2024-06-04 00:52 UTC, ho991217 commented on src/app/api/is-expired-refresh.ts
> +};
`is`라는 접두사는 `boolean` 값을 반환하는 함수에 적합한 접두사라고 생각해요! 

또한, 이 함수에 여러가지 책임이 담겨있다는 생각이 드네요!
리프레시 토큰 만료를 `assert`해주는 함수와 그것을 처리해주는 부분으로 나누어주면 어떨까요?

2024-06-04 00:52 UTC, ho991217 commented on src/app/login/page.tsx
> +      credentials: 'include',
이 부분도 `customFetch`의 기본값으로 넣어줄 수 있을 것 같아요!

2024-06-04 03:19 UTC, hyunwlee-dev approved these changes
많이 배웠습니다. 수고하셨습니다!

2024-06-04 05:31 UTC, hyunwlee-dev commented on src/constant/api.ts
> +  lineup: (id?: string) => (id ? `/admin/festival/${id}` : '/admin/festival'),
lineup -> festival로 변경해주세요!

2024-06-04 05:48 UTC, kd02109 commented
- `credential:include`, `"content-type": "application/json" 이 고정적으로 포함되도록 변경
- 쿠키 삭제 함수를 서버 액션으로 유틸 함수로 분리
- isExpiredRefresh 함수 명을 checkStatusForRefreshToken으로 변경

2024-06-04 05:58 UTC, merged